// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace IndexModuleScssNamespace {
    export interface IIndexModuleScss {
        appBar: string;
        arrDwn: string;
        arrowDown: string;
        avatar: string;
        btnLog: string;
        btnText: string;
        calendarWrapper: string;
        chipColor: string;
        closeBtn: string;
        dateTime: string;
        gMenuIcon: string;
        generalMenu: string;
        hide: string;
        icUser: string;
        langPicker: string;
        leftSide: string;
        logoutBtn: string;
        menu: string;
        menuBtn: string;
        muiListItemTextPrimary: string;
        onlineUsers: string;
        rightSide: string;
        textUser: string;
        timer: string;
        toolbar: string;
        user: string;
    }
}

declare const IndexModuleScssModule: IndexModuleScssNamespace.IIndexModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: IndexModuleScssNamespace.IIndexModuleScss;
};

export = IndexModuleScssModule;
