// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace IndexModuleScssNamespace {
    export interface IIndexModuleScss {
        active: string;
        activeIcon: string;
        closeBtn: string;
        container: string;
        drawer: string;
        drawerHeader: string;
        leftSide: string;
        list: string;
        listIcon: string;
        listItem: string;
        listText: string;
        muiListItemIconRoot: string;
        muiPaperRoot: string;
        muiTypographyRoot: string;
        openBtn: string;
        rightSide: string;
        sidebarBtn: string;
    }
}

declare const IndexModuleScssModule: IndexModuleScssNamespace.IIndexModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: IndexModuleScssNamespace.IIndexModuleScss;
};

export = IndexModuleScssModule;
