import {helper} from '@shared/helpers';

const {getSingle} = helper;
interface IData {
    id: number;
    time: string;
    race: number;
    g_num: number;
    bus_name: string;
    gos_number: string;
    kpp1: string;
    tab_name: string;
    day_type: string;
    driver_name: string;
}

export const data: IData[] = [
    {
        id: 1,
        time: '6:00 - 21:00',
        race: 12,
        g_num: 470,
        bus_name: 'M.Benz Low Floor',
        gos_number: '01 437 YCA',
        kpp1: 'Қўйлиқ деҳқон бозори',
        tab_name: '6324',
        day_type: getSingle(),
        driver_name: 'А.р.Абдимажид угли',
    },
    {
        id: 2,
        time: '6:00 - 21:00',
        race: 12,
        g_num: 470,
        bus_name: 'M.Benz Low Floor',
        gos_number: '01 437 YCA',
        kpp1: 'Қўйлиқ деҳқон бозори',
        tab_name: '6324',
        day_type: getSingle(),
        driver_name: 'А.р.Абдимажид угли',
    },
    {
        id: 3,
        time: '6:00 - 21:00',
        race: 12,
        g_num: 470,
        bus_name: 'M.Benz Low Floor',
        gos_number: '01 437 YCA',
        kpp1: 'Қўйлиқ деҳқон бозори',
        tab_name: '6324',
        day_type: getSingle(),
        driver_name: 'А.р.Абдимажид угли',
    },
    {
        id: 4,
        time: '6:00 - 21:00',
        race: 12,
        g_num: 470,
        bus_name: 'M.Benz Low Floor',
        gos_number: '01 437 YCA',
        kpp1: 'Қўйлиқ деҳқон бозори',
        tab_name: '6324',
        day_type: getSingle(),
        driver_name: 'А.р.Абдимажид угли',
    },
    {
        id: 5,
        time: '6:00 - 21:00',
        race: 12,
        g_num: 470,
        bus_name: 'M.Benz Low Floor',
        gos_number: '01 437 YCA',
        kpp1: 'Қўйлиқ деҳқон бозори',
        tab_name: '6324',
        day_type: getSingle(),
        driver_name: 'А.р.Абдимажид угли',
    },
    {
        id: 6,
        time: '6:00 - 21:00',
        race: 12,
        g_num: 470,
        bus_name: 'M.Benz Low Floor',
        gos_number: '01 437 YCA',
        kpp1: 'Қўйлиқ деҳқон бозори',
        tab_name: '6324',
        day_type: getSingle(),
        driver_name: 'А.р.Абдимажид угли',
    },
    {
        id: 7,
        time: '6:00 - 21:00',
        race: 12,
        g_num: 470,
        bus_name: 'M.Benz Low Floor',
        gos_number: '01 437 YCA',
        kpp1: 'Қўйлиқ деҳқон бозори',
        tab_name: '6324',
        day_type: getSingle(),
        driver_name: 'А.р.Абдимажид угли',
    },
    {
        id: 8,
        time: '6:00 - 21:00',
        race: 12,
        g_num: 470,
        bus_name: 'M.Benz Low Floor',
        gos_number: '01 437 YCA',
        kpp1: 'Қўйлиқ деҳқон бозори',
        tab_name: '6324',
        day_type: getSingle(),
        driver_name: 'А.р.Абдимажид угли',
    },
    {
        id: 9,
        time: '6:00 - 21:00',
        race: 12,
        g_num: 470,
        bus_name: 'M.Benz Low Floor',
        gos_number: '01 437 YCA',
        kpp1: 'Қўйлиқ деҳқон бозори',
        tab_name: '6324',
        day_type: getSingle(),
        driver_name: 'А.р.Абдимажид угли',
    },
    {
        id: 10,
        time: '6:00 - 21:00',
        race: 12,
        g_num: 470,
        bus_name: 'M.Benz Low Floor',
        gos_number: '01 437 YCA',
        kpp1: 'Қўйлиқ деҳқон бозори',
        tab_name: '6324',
        day_type: getSingle(),
        driver_name: 'А.р.Абдимажид угли',
    },
    {
        id: 11,
        time: '6:00 - 21:00',
        race: 12,
        g_num: 470,
        bus_name: 'M.Benz Low Floor',
        gos_number: '01 437 YCA',
        kpp1: 'Қўйлиқ деҳқон бозори',
        tab_name: '6324',
        day_type: getSingle(),
        driver_name: 'А.р.Абдимажид угли',
    },
    {
        id: 12,
        time: '6:00 - 21:00',
        race: 12,
        g_num: 470,
        bus_name: 'M.Benz Low Floor',
        gos_number: '01 437 YCA',
        kpp1: 'Қўйлиқ деҳқон бозори',
        tab_name: '6324',
        day_type: getSingle(),
        driver_name: 'А.р.Абдимажид угли',
    },
    {
        id: 13,
        time: '6:00 - 21:00',
        race: 12,
        g_num: 470,
        bus_name: 'M.Benz Low Floor',
        gos_number: '01 437 YCA',
        kpp1: 'Қўйлиқ деҳқон бозори',
        tab_name: '6324',
        day_type: getSingle(),
        driver_name: 'А.р.Абдимажид угли',
    },

    {
        id: 14,
        time: '6:00 - 21:00',
        race: 12,
        g_num: 470,
        bus_name: 'M.Benz Low Floor',
        gos_number: '01 437 YCA',
        kpp1: 'Қўйлиқ деҳқон бозори',
        tab_name: '6324',
        day_type: getSingle(),
        driver_name: 'А.р.Абдимажид угли',
    },

    {
        id: 15,
        time: '6:00 - 21:00',
        race: 12,
        g_num: 470,
        bus_name: 'M.Benz Low Floor',
        gos_number: '01 437 YCA',
        kpp1: 'Қўйлиқ деҳқон бозори',
        tab_name: '6324',
        day_type: getSingle(),
        driver_name: 'А.р.Абдимажид угли',
    },
];
