// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace LayoutModuleScssNamespace {
    export interface ILayoutModuleScss {
        container: string;
        drawHead: string;
        mainBox: string;
        makeStylesToolbar9: string;
        muiToolbarGutters: string;
        outlet: string;
    }
}

declare const LayoutModuleScssModule: LayoutModuleScssNamespace.ILayoutModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: LayoutModuleScssNamespace.ILayoutModuleScss;
};

export = LayoutModuleScssModule;
